Repository 7-final-project/restaurant, pull requests merged in 2025-01, with the labels that each got.

#12 application-prod.yml 수정 요구 사항 반영
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ⚙ Setting, ✨ Feature, 🚀 Deploy

#21 지역 엔티티 생성
  src/main/java/com/qring/restaurant/application/v1/res/RestaurantGetByIdResDTOV1.java
  src/main/java/com/qring/restaurant/application/v1/res/RestaurantPostResDTOV1.java
  src/main/java/com/qring/restaurant/application/v1/res/RestaurantSearchResDTOV1.java
  src/main/java/com/qring/restaurant/application/v1/service/RestaurantServiceV1.java
  src/main/java/com/qring/restaurant/domain/model/RegionEntity.java
  src/main/java/com/qring/restaurant/domain/model/RestaurantEntity.java
  src/main/java/com/qring/restaurant/domain/repository/RegionRepository.java
  src/main/java/com/qring/restaurant/infrastructure/InitialRegionDataInserter.java
  src/main/java/com/qring/restaurant/infrastructure/repository/JpaRegionRepository.java
  src/main/java/com/qring/restaurant/infrastructure/repository/RegionRepositoryImpl.java
  src/main/java/com/qring/restaurant/presentation/v1/req/PostRestaurantReqDTOV1.java
  src/main/java/com/qring/restaurant/presentation/v1/req/PutRestaurantReqDTOV1.java
Labels: ✨ Feature, 🔨 Refactor

#24 운영환경 설정을 위한 YML 파일 구성 및 클래스 버전별 분류 제거
  src/main/java/com/qring/restaurant/application/res/CategoryGetByIdResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/CategoryPostResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/CategoryTableGetResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/RestaurantExistsByIdResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/RestaurantGetByIdResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/RestaurantIdTableResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/RestaurantPostResDTOV1.java
  src/main/java/com/qring/restaurant/application/res/RestaurantSearchResDTOV1.java
  src/main/java/com/qring/restaurant/application/scheduler/OperationStatusScheduler.java
  src/main/java/com/qring/restaurant/application/service/CategoryServiceV1.java
  src/main/java/com/qring/restaurant/application/service/RestaurantServiceV1.java
  src/main/java/com/qring/restaurant/infrastructure/docs/CategoryControllerSwagger.java
  src/main/java/com/qring/restaurant/infrastructure/docs/RestaurantControllerSwagger.java
  src/main/java/com/qring/restaurant/infrastructure/scheduler/OperationStatusSchedulerImpl.java
  src/main/java/com/qring/restaurant/presentation/controller/CategoryControllerV1.java
  src/main/java/com/qring/restaurant/presentation/controller/RestaurantControllerV1.java
  src/main/java/com/qring/restaurant/presentation/req/PostCategoryReqDTOV1.java
  src/main/java/com/qring/restaurant/presentation/req/PostRestaurantReqDTOV1.java
  src/main/java/com/qring/restaurant/presentation/req/PutCategoryDTOV1.java
  src/main/java/com/qring/restaurant/presentation/req/PutRestaurantReqDTOV1.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/qring/restaurant/RestaurantEntityApplicationTests.java
Labels: ⚙ Setting, 🔨 Refactor, 🚀 Deploy
